### ISSUE TITLE
VC++2015 redistributable requirement

### ISSUE THREAD

**Issue by smoogipoo** [Tom94/stbi-sharp#2]
This project seems to depend on the VC++2015 redistributable package, which did not come pre-installed with a W10H install.

[Upon looking around](https://stackoverflow.com/questions/1581105/running-c-binaries-without-the-runtime-redistributable-server2k3-xpsp3), it may be resolved by including the [`/MT`](https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=vs-2019) option to the compiler arguments:
https://github.com/Tom94/stbi-sharp/blob/7270b520b423e127e47680739be67c5ddbe8f829/libstbi/CMakeLists.txt#L14

**Comment by Tom94** [comment]
Ouch, that line in the CMake file was originally meant to do the static linking you desribe. Seem like I made a mistake in choosing the appropriate argument. Thank for pointing it out! :)

Gonna test/debug this on the weekend.

**Comment by Tom94** [comment]
Apologies for the delay---didn't get to it last weekend after all.
